/*
 * Copyright 2026 PicturePlayer;Nserly
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package top.nserly.PicturePlayer.NComponent.Frame;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import top.nserly.GUIStarter;
import top.nserly.PicturePlayer.NComponent.Component.PaintPicturePanel;
import top.nserly.PicturePlayer.Size.SizeOperate;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class FullScreenFrame extends JFrame {
    private final JPanel panel1;
    private final JButton ExitButton;
    private final JLabel PicturePath;
    private PaintPicturePanel.ImageCanvas imageCanvas;
    private static final GraphicsDevice screen;
    private static final boolean IS_SUPPORTED;

    static {
        screen = GraphicsEnvironment
                .getLocalGraphicsEnvironment()
                .getDefaultScreenDevice();

        IS_SUPPORTED = screen.isFullScreenSupported();
    }

    public FullScreenFrame() {
        {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
            panel1 = new JPanel();
            panel1.setLayout(new BorderLayout(0, 0));
            final JPanel panel2 = new JPanel();
            panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
            panel2.setFocusable(false);
            panel2.setRequestFocusEnabled(false);
            panel1.add(panel2, BorderLayout.NORTH);
            ExitButton = new JButton();
            ExitButton.setFocusPainted(true);
            ExitButton.setFocusable(false);
            ExitButton.setRequestFocusEnabled(false);
            ExitButton.setText("X");
            panel2.add(ExitButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
            final Spacer spacer1 = new Spacer();
            panel2.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
            PicturePath = new JLabel();
            PicturePath.setFocusable(false);
            PicturePath.setRequestFocusEnabled(false);
            PicturePath.setText("");
            panel2.add(PicturePath, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        }
        init();
    }

    public FullScreenFrame(PaintPicturePanel.ImageCanvas imageCanvas) {
        this();
        setImageCanvas(imageCanvas);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void init() {
        setIconImage(GUIStarter.SOFTWARE_FRAME_ICON);
        setUndecorated(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setSize(SizeOperate.FreeOfScreenSize);
        getContentPane().add(panel1);
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                if (!isShowing()) return;
                PaintPicturePanel.paintPicture.sizeOperate.incomeWindowDimension(imageCanvas.getSize());
                PaintPicturePanel.paintPicture.sizeOperate.update(false);
            }
        });
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                PaintPicturePanel.paintPicture.imageCanvas.setFullScreen(false);
            }
        });
        ExitButton.addActionListener(_ -> {
            PaintPicturePanel.paintPicture.imageCanvas.setFullScreen(false);
        });
    }

    public void setVisible(boolean visible) {
        this.setFullScreen(visible);
        if (visible && imageCanvas != null) {
            PicturePath.setText(imageCanvas.getPath());
            imageCanvas.requestFocusInWindow();
            imageCanvas.repaint();
        }
    }

    private synchronized void setFullScreen(boolean enable) {
        if (enable && !isVisible()) {
            super.setVisible(true);
            if (IS_SUPPORTED)
                screen.setFullScreenWindow(this);
        } else if (!enable && isVisible()) {
            if (IS_SUPPORTED)
                screen.setFullScreenWindow(null);
            super.setVisible(false);
        }
    }


    public void setImageCanvas(PaintPicturePanel.ImageCanvas imageCanvas) {
        if (imageCanvas == null) return;
        if (this.imageCanvas != null)
            panel1.remove(this.imageCanvas);
        this.imageCanvas = imageCanvas;
        panel1.add(imageCanvas, BorderLayout.CENTER);
    }

}
