package NComponent;

import Runner.Main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class FullScreenWindow extends JFrame {

    private JPanel panel1;
    private PaintPicture.ImageCanvas imageCanvas;

    public FullScreenWindow() {
        init();
    }

    private void init() {
        setUndecorated(false);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        add(panel1);
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                if (!isShowing()) return;
                PaintPicture.paintPicture.sizeOperate.incomeWindowDimension(imageCanvas.getSize());
                PaintPicture.paintPicture.sizeOperate.update(false);
            }
        });
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                PaintPicture.paintPicture.add(imageCanvas, BorderLayout.CENTER);
                setVisible(false);
                Main.main.setVisible(true);
                PaintPicture.paintPicture.sizeOperate.incomeWindowDimension(imageCanvas.getSize());
                PaintPicture.paintPicture.sizeOperate.update(false);
            }
        });
    }

    public FullScreenWindow(PaintPicture.ImageCanvas imageCanvas) {
        init();
        setImageCanvas(imageCanvas);
    }

    public void setVisible(boolean visible) {
        super.setVisible(visible);
        PaintPicture.paintPicture.sizeOperate.incomeWindowDimension(imageCanvas.getSize());
        PaintPicture.paintPicture.sizeOperate.update(false);
        if (!visible) getGraphics().dispose();
    }

    public void setImageCanvas(PaintPicture.ImageCanvas imageCanvas) {
        if (imageCanvas == null) return;
        if (this.imageCanvas != null)
            panel1.remove(this.imageCanvas);
        this.imageCanvas = imageCanvas;
        panel1.add(imageCanvas, BorderLayout.CENTER);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
