package Component;

import Tools.Component.WindowLocation;
import Tools.String.Formation;
import Version.Download.DownloadUpdate;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class DownloadUpdateFrame extends JFrame {
    private JLabel Title;
    private JLabel DownloadTotalProgress;
    private JProgressBar TotalProgress;
    private JLabel CurrentDownloadProgress;
    private JProgressBar CurrentProgress;
    private JLabel CurrentPercentOfHundred;
    private JLabel TotalPercentOfHundred;
    private JPanel Main;
    private JLabel SpeedLabel;
    private JLabel DownloadCountings;
    private DownloadUpdate downloadUpdate;


    public DownloadUpdateFrame(DownloadUpdate update) {
        setContentPane(Main);
        Formation formation = new Formation(Title.getText());
        formation.Change("Version", update.NewVersionName);
        formation.Change("VersionID", String.valueOf(update.NewVersionID));
        Title.setText(formation.getResult().toString());
        downloadUpdate = update;
        DownloadCountings.setText(DownloadCountings.getText() + "\n{current}/{total}");
        setSize(480, 230);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    public void setVisible(boolean b) {
        if (b && !isVisible()) {
            AdvancedDownloadSpeed advancedDownloadSpeed = new AdvancedDownloadSpeed(downloadUpdate, TotalProgress, CurrentProgress, SpeedLabel, TotalPercentOfHundred, CurrentPercentOfHundred, DownloadCountings);
            Point location = WindowLocation.ParentCenter(Runner.Main.main, getWidth(), getHeight());
            setLocation(location);
        }
        Runner.Main.main.setVisible(!b);
        super.setVisible(b);
    }

    public void dispose() {
        super.dispose();
        Runner.Main.main.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Main = new JPanel();
        Main.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        Title = new JLabel();
        Font TitleFont = this.$$$getFont$$$(null, -1, 18, Title.getFont());
        if (TitleFont != null) Title.setFont(TitleFont);
        Title.setText("下载{Version}({VersionID}}中...");
        Main.add(Title, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        Main.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        DownloadTotalProgress = new JLabel();
        DownloadTotalProgress.setText("下载总进度：");
        panel1.add(DownloadTotalProgress, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        TotalProgress = new JProgressBar();
        panel1.add(TotalProgress, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        TotalPercentOfHundred = new JLabel();
        TotalPercentOfHundred.setText("{Total}%");
        panel1.add(TotalPercentOfHundred, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        Main.add(panel2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        CurrentDownloadProgress = new JLabel();
        CurrentDownloadProgress.setText("当前下载进度:");
        panel2.add(CurrentDownloadProgress, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        CurrentProgress = new JProgressBar();
        panel2.add(CurrentProgress, new GridConstraints(0, 1, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        SpeedLabel = new JLabel();
        SpeedLabel.setText("下载速率：");
        panel2.add(SpeedLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        DownloadCountings = new JLabel();
        DownloadCountings.setText("下载数：");
        panel2.add(DownloadCountings, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        CurrentPercentOfHundred = new JLabel();
        CurrentPercentOfHundred.setText("{Current}%");
        panel2.add(CurrentPercentOfHundred, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Main;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
